### ISSUE TITLE
Demo server

### ISSUE THREAD

**Issue by wzshiming** [wzshiming/jitdi#4]

**Comment by wzshiming** [comment]
```yaml
# jitdi-config.yaml
apiVersion: jitdi.zsm.io/v1alpha1
kind: Image
metadata:
  name: file-test
spec:
  match: "k8s/{base}/{file}:{tag}"
  baseImage: "docker.io/library/{base}:latest"
  platforms:
  - architecture: "amd64"
    os: "linux"
  - architecture: "arm64"
    os: "linux"
  mutates:
  - file:
      source: "https://dl.k8s.io/{tag}/bin/{GOOS}/{GOARCH}/{file}"
      destination: "/usr/local/bin/{file}"
      mode: '0755'
  storageImage: "ghcr.io/wzshiming/jitdi/test:k8s-{base}-{file}-{tag}"
---
apiVersion: jitdi.zsm.io/v1alpha1
kind: Image
metadata:
  name: ollama-test
spec:
  match: "ollama/{model}:{tag}"
  baseImage: "docker.io/ollama/ollama:latest"
  mutates:
  - ollama:
      model: "registry.ollama.ai/library/{model}:{tag}"
      workDir: "/root/.ollama/models"
      modelName: "{model}"
  platforms:
    - architecture: "amd64"
      os: "linux"
    - architecture: "arm64"
      os: "linux"
  storageImage: "ghcr.io/wzshiming/jitdi/test:ollama-{model}-{tag}"
---
apiVersion: jitdi.zsm.io/v1alpha1
kind: Registry
metadata:
  name: ghcr.io
spec:
  authentication:
    baseAuth:
      username: "wzshiming"
      password: "{TOKEN}"
```

**Comment by wzshiming** [comment]
```yaml
version: '3'
services:
  jitdi:
    image: ghcr.io/wzshiming/jitdi/jitdi:v0.0.8
    ports:
    - "8888:8888"
    command:
    - --cache=/var/cache/
    - --config=/config.yaml
    - --storage-image-proxy=cr.zsm.io
    volumes:
    - ./jitdi-config.yaml:/config.yaml:ro
```
